kind: pipeline
name: default

steps:
- name: build image
  image: ruby:2.7.1-slim
  commands:
  - apt-get update -y && apt-get install -y curl build-essential
  - curl https://get.docker.io/builds/Linux/x86_64/docker-latest -o /usr/local/bin/docker
  - chmod +x /usr/local/bin/docker
  - gem install bundler:2.1.4
  - bundle config set deployment 'true'
  - bundle config set without 'development test'
  - bundle install
  - make build_docker
  - make push_docker
